---
# This workflow runs tests and lint checks on push
name: Checks

# trigger workflow on push to any branch
on: [push]

jobs:
    test-lint:
        # user friendly name
        name: Test and Lint
        # github runner
        runs-on: ubuntu-24.04
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              run: docker compose run --rm app sh -c "python manage.py test"
            - name: Lint
              run: docker compose run --rm app sh -c "ruff check ."
